### ISSUE TITLE
Feature Request: async-std-runtime

### ISSUE THREAD

**Issue by c-classen** [stevepryde/thirtyfour_query#7]
I was using this crate in order to wait for a `div` that is present the whole time to change its text to a specific one, so I was using this code:
```rust
self.query(By::Css("div.errorMsg"))
    .wait(Duration::from_secs(1), Duration::from_millis(100))
    .with_text(error_msg.to_owned()).first().await?;
```

However, at runtime, this failed with the following message:
```
thread 'register' panicked at 'there is no timer running, must be called from the context of Tokio runtime'
```
This made sense because I was using async-std since the tests were part of a web server running with tide.

It would be nice if there was an `async-std-runtime` crate feature for thirtyfour_query just like there is one for thirtyfour itself

**Comment by stevepryde** [comment]
Ah yes good point. This should just be a matter of exposing the feature flags and forwarding them on.

**Comment by stevepryde** [comment]
Fixed in v0.5.3

**Comment by c-classen** [comment]
Thank you for the quick response and your work on this project in general. Unfortunately, my problem still persists with v0.5.3, since `delay_for` from tokio is used in the thirtyfour_query code. I created a pull request (#8) that resolves this issue for me.
